name: dotnet

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore tests/CpuEmulator.Tests/CpuEmulator.Tests.csproj

      - name: Test
        run: dotnet test tests/CpuEmulator.Tests/CpuEmulator.Tests.csproj --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory "${{ github.workspace }}/TestResults"

      - name: List test results
        if: always()
        run: find "${{ github.workspace }}" -name "*.trx" -print

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: dotnet-tests
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: TestResults
